### ISSUE TITLE
titleStyle property is not working

### ISSUE THREAD

**Issue by SivaDotRender** [n4kz/react-native-material-buttons#5]
I am trying to use the `titleStyle` property to set the style of a `TextButton` text but it does not appear to be working:

    <TextButton titleStyle={styles.buttonText} style={styles.button}
        title = {title}
    >

    const styles = StyleSheet.create({
      button: {
      backgroundColor: 'green',
      flex: 0.9,
      height: "100%",
      width: "100%",
    },
    buttonText: {
    color:'red',
    }

The Text color remains black in this case. 

Also, is there a way to disable the automatic capitalization in TextButton titleStyle? For example, even if title is set to "AaAaAa" it is displayed as "AAAAAA"

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. I've released `0.6.0` and now you can override `textTransform` style property and get lower or mixed case. To change button title color please use  `titleColor` and `disabledTitleColor` properties.
