### ISSUE TITLE
How could change to lower case of button text?

### ISSUE THREAD

**Issue by macroday** [n4kz/react-native-material-buttons#7]
Hi,

Please tell me to change the text case in to lower case or upper case of buttons.

**Comment by maestrovsmaster** [comment]
>>macroday
>>Please tell me to change the text case in to lower case or upper case of buttons.


Hi!
me too! Thanks!

**Comment by yasir-netlinks** [comment]
Any success ?

**Comment by emanuelboros** [comment]
There is a workaround (which honestly I don't like), override the `toUpperCase` native function. 
`
String.prototype.toUpperCase = function() {
  return this + "";
};
`

The other one is to update the code, I could do it, but there are 2 PRs since 2018 and the owner didn't bother to look over :( .

**Comment by macroday** [comment]
That's why i moved to **flutter**

**Comment by farshidshahmoradi1996** [comment]
same issue

**Comment by n4kz** [comment]
Thanks for question and sorry for delayed reply. I've released `0.6.0` and now you can override `textTransform` style property and get lower or mixed case.
